version: "3.5"

services:
  mysql:
    image: centos/mysql-80-centos8:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nukagit
      MYSQL_USER: nukagit
      MYSQL_PASSWORD: password
      MYSQL_LOWER_CASE_TABLE_NAMES: 1
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql/:/var/lib/mysql/data:rw

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: minio99
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/minio:/data:rw
    command: server /data --console-address ":9001"
  mc:
    image: minio/mc:latest
    container_name: mc
    restart: "no"
    depends_on:
      - minio
    entrypoint: /bin/sh
    command: -c "mc alias set minio http://minio:9000 minio99 minio123 && mc mb minio/nukagit"
